export type Group = {id:string; stream:string; name:string; total:number; renewed:number|null; source:string; updated:string};
export const sourceBase='https://juz40-edu.kz/headTeacher/subjects/e6d6f884-5f5a-46c0-9b5a-929051b9a3d8/';
export const streams=[
 {id:'gum-sep',label:'ГУМ · Қыркүйек',title:'Математикалық сауаттылық ГУМ SMART ҚЫРКҮЙЕК 11 СЫНЫП 2027',source:sourceBase+'25138844-007f-49d4-96a6-a440ce7bf62e'},
 {id:'tech-sep',label:'ТЕХ · Қыркүйек',title:'Математикалық сауаттылық ТЕХ SMART ҚЫРКҮЙЕК 11 СЫНЫП 2027',source:sourceBase+'76d53d0b-c6d2-4702-90e5-7238c37df31d'},
 {id:'tech-aug',label:'ТЕХ · Тамыз',title:'Математикалық сауаттылық ТЕХ SMART ТАМЫЗ 11 СЫНЫП 2027',source:sourceBase+'0064df32-378f-43c2-b85c-68a9faf8d3b1'},
 {id:'gum-aug',label:'ГУМ · Тамыз',title:'Математикалық сауаттылық ГУМ SMART ТАМЫЗ 11 СЫНЫП 2027',source:sourceBase+'cb16500f-a474-4be1-9956-00becd85f8ea'},
 {id:'gum-jul',label:'ГУМ · Шілде',title:'Математикалық сауаттылық ГУМ SMART ШІЛДЕ 11 СЫНЫП 2027',source:sourceBase+'7cadc9ae-b27c-4f7e-803f-36bf2ed9ede0'},
 {id:'tech-jul',label:'ТЕХ · Шілде',title:'Математикалық сауаттылық ТЕХ SMART ШІЛДЕ 11 СЫНЫП 2027',source:sourceBase+'419674db-701a-4f1e-a08e-056113fd886e'}
];
const gum=['Зарина Мукашева','Ерасыл Жанболат','Жаннұр Шакизада','Ақүрпек Тұрсынқұл','Әсемай Әбдіжәмил','Арайлым Әбушахман','Айзере Сағатқызы','Айым Нұртулеу','Зере Мұратбай','Эльнура Ыгышова','Ақнұр Нүсіп','Аружан Талғат','Балнұр Мырзабек','Абылай Сабыров','Інжу Қырықпа','Раушан Жұмабек','Назерке Нұрболқызы','Жазира Тагайбекова','Нұрдос Ырысбек','Анель Жоламан','Гулмира Мухаммед'];
const tech=['Эльназ Ермек','Шұғыла Амангелді','Аида Марбек','Бағжан Болат','Нұртас Жантас','Молдир Скакова','Меруерт Асембаева','Ақниет Серікбай','Роза Жүніс','Шырын Нұрланқызы','Ақбота Құдайберген'];
const aug:[string,number,number][]=[['Асем Сейтимова',79,69],['Нұрлы Қайрғалиева',79,71],['Лэйла Ерсайнова',81,70],['Ақбота Ғазиз',82,71],['Еркеназ Әмзебекова',82,72]];
const gumJuly:[string,number,number|null][]=[['Ерасыл Ақжігітов',0,null],['Аружан Талғат',0,null],['Жазира Тагайбекова',0,null],['Әбдіманап Әбілда',0,null],['Эльнура Ыгышова',0,null],['Молдир Скакова',0,null],['Айзере Сағатқызы',15,1],['Жаннұр Шакизада',15,2],['Эльназ Ермек',19,1],['Зерделі Тоқтарбайқызы',93,65],['Эльвира Ерлікқызы',94,73],['Аяжан Саркеева',96,70],['Дильназ Мухитова',96,73],['Диана Сайлаугалиева',97,69],['Ернар Алтынбек',98,71]];
const techJuly:[string,number,number|null][]=[['Ақниет Серікбай',0,null],['Аружан Нагизбекова',0,null],['Роза Жүніс',0,null],['Айым Нұртулеу',0,null],['Ерасыл Жанболат',0,null],['Ақүрпек Тұрсынқұл',0,null],['Жайнар Сейдалиев',120,81],['Ақнұр Ұзақова',120,84],['Дастан Қайыржанұлы',120,79]];
const gumAugust:[string,number,number|null][]=[['Нұрдос Ырысбек',0,null],['Әсемай Әбдіжамил',0,null],['Абылай Сабыров',0,null],['Зере Мұратбай',0,null],['Анель Жоламан',0,null],['Бағжан Болат',0,null],['Арайлым Әбушахман',0,null],['Гулмира Мухаммед',0,null],['Ақниет Бодаубек',0,null],['Мөлдір Дәлубайқызы',85,66],['Тамирлан Баяхмет',86,67],['Адина Мұраталы',86,69],['Бақберген Амангелді',86,68],['Жібек Қуат',87,69],['Алихан Жаумитов',87,72],['Іңкәр Жәрдемхан',88,72],['Аяулым Серік',88,70],['Іңкәр Шохан',88,68]];
export const baseline:Group[]=[...gum.map((name,i)=>({id:`gum-sep-${i+1}`,stream:'gum-sep',name,total:i===0?73:i<10?75:i<19?76:77,renewed:null})),...tech.map((name,i)=>({id:`tech-sep-${i+1}`,stream:'tech-sep',name,total:i===0?72:i<7?73:i<10?74:75,renewed:null})),...aug.map(([name,total,renewed],i)=>({id:`tech-aug-${i+1}`,stream:'tech-aug',name,total,renewed})),...gumAugust.map(([name,total,renewed],i)=>({id:`gum-aug-${i+1}`,stream:'gum-aug',name,total,renewed})),...gumJuly.map(([name,total,renewed],i)=>({id:`gum-jul-${i+1}`,stream:'gum-jul',name,total,renewed})),...techJuly.map(([name,total,renewed],i)=>({id:`tech-jul-${i+1}`,stream:'tech-jul',name,total,renewed}))].filter(g=>g.stream.endsWith('sep')||(g.renewed!==null&&g.renewed>0)).map(g=>({...g,total:g.renewed??g.total,renewed:null,source:'Жаңа айдың бастапқы тізімі',updated:'2026-09-08'}));
export type Entry={id:string;kind:'case'|'practice';groupId:string;title:string;reason:string;method:string;result:string;status:string;followUp:string;fileId:string|null;fileName:string|null;created:string;author:string;userId:string};
export function rate(renewed:number,total:number){return total>0?renewed/total*100:null}
export function summarize(groups:Group[]){const known=groups.filter(g=>g.renewed!==null); const denominator=known.reduce((n,g)=>n+g.total,0);const renewed=known.reduce((n,g)=>n+(g.renewed??0),0);return {total:groups.reduce((n,g)=>n+g.total,0),known:known.length,denominator,renewed,rr:rate(renewed,denominator),missing:groups.length-known.length}}
export const statuses=[{value:'contact',label:'Байланыс орнатылуда'},{value:'promised',label:'Төлемге уәде берді'},{value:'retained',label:'Курста қалды'},{value:'left',label:'Курстан шықты'}];
